site_name: Go Runtime Insider
site_url: https://liwh1227.github.io/go-runtime-insider/
repo_url: https://github.com/liwh1227/go-runtime-insider
repo_name: go-runtime-insider

theme:
  name: material
  features:
    - navigation.tabs # 顶部导航栏
    - navigation.sections # 侧边栏分组
    - content.code.copy # 代码块复制按钮
  palette:
    scheme: default # 支持暗黑模式切换
    primary: teal
    accent: purple

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

nav:
  - Home: README.md
  - 'Module 1: Scheduler':
      - '01 Load Balance': 01_scheduler/01_load_balance/README.md
      - '02 Preemption': 01_scheduler/02_preemption/README.md
      - '03 Stealing': 01_scheduler/03_stealing_hack/README.md
  - 'Module 2: Memory':
      - '01 Allocator': 02_memory/01_allocator/README.md